kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $.Chart.Name }}
spec:
  replicas: {{ .Values.mosquittoBroker.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
        version: "{{ $.Chart.Name }}-{{ .Values.mosquittoBroker.image.tag }}"
    spec:
      initContainers:
        - name: config-substitution
          image: bhgedigital/envsubst:latest
          env:
            - name: MQTT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mosquittoBroker.database.passwordSecretName }}
                  key: {{ .Values.mosquittoBroker.database.passwordSecretKey }}
          command:
            - sh
            - -c
            - |
              envsubst < /etc/mosquitto/conf.d-template/go-auth.conf > /etc/mosquitto/conf.d/go-auth.conf
          volumeMounts:
            - name: {{ $.Chart.Name }}-configmap
              mountPath: /etc/mosquitto/conf.d-template
              readOnly: true
            - name: config-processed
              mountPath: /etc/mosquitto/conf.d
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ .Values.mosquittoBroker.image.registry }}/{{ .Values.mosquittoBroker.image.repository }}:{{ .Values.mosquittoBroker.image.tag }}"
          imagePullPolicy: {{ .Values.mosquittoBroker.image.pullPolicy }}
          ports:
            - name: mos-cert
              containerPort: 8884
              protocol: TCP
            - name: mos-userpass
              containerPort: 8885
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.mosquittoBroker.resources.limits.cpu }}
              memory: {{ .Values.mosquittoBroker.resources.limits.memory }}
            requests:
              cpu: {{ .Values.mosquittoBroker.resources.requests.cpu }}
              memory: {{ .Values.mosquittoBroker.resources.requests.memory }}
          volumeMounts:
            - name: config-processed
              mountPath: /etc/mosquitto/conf.d
              readOnly: true
            - name: secret-ca-crt
              mountPath: /etc/mosquitto/ca_certificates
              readOnly: true
            - name: secret-server-key
              mountPath: /etc/mosquitto/certs
              readOnly: true
      volumes:
        - name: "{{ $.Chart.Name }}-configmap"
          configMap:
            name: "{{ $.Chart.Name }}-configmap"
        - name: config-processed
          emptyDir: {}
        - name: secret-ca-crt
          secret:
            secretName: ca-keys
        - name: secret-server-key
          secret:
            secretName: server-keys
      restartPolicy: Always
