kind: Service
apiVersion: v1
metadata:
  name: {{ $.Chart.Name }}-svc
  labels:
    app: {{ $.Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - name: mos-cert
      port: 8884
      targetPort: 8884
      protocol: TCP
    - name: mos-userpass
      port: 8885
      targetPort: 8885
      protocol: TCP
  selector:
    app: {{ $.Chart.Name }}
