kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $.Chart.Name }}
spec:
  replicas: {{ .Values.chirpstackGateway.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
        version: "{{ $.Chart.Name }}-{{ .Values.chirpstackGateway.image.tag }}"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      # Restrict to fsn1 to ensure Cloudfleet creates only one LB
      nodeSelector:
        topology.kubernetes.io/region: fsn1
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ .Values.chirpstackGateway.image.registry }}/{{ .Values.chirpstackGateway.image.repository }}:{{ .Values.chirpstackGateway.image.tag }}"
          imagePullPolicy: {{ .Values.chirpstackGateway.image.pullPolicy }}
          ports:
            - name: udp
              containerPort: 1700
              protocol: UDP
          resources:
            {{- toYaml .Values.chirpstackGateway.resources | nindent 12 }}
          volumeMounts:
            - name: {{ $.Chart.Name }}-configmap
              mountPath: /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml
              subPath: chirpstack-gateway-bridge.toml
      volumes:
        - name: "{{ $.Chart.Name }}-configmap"
          configMap:
            name: "{{ $.Chart.Name }}-configmap"
      restartPolicy: Always
