kind: Service
apiVersion: v1
metadata:
  name: {{ $.Chart.Name }}-svc
  labels:
    app: {{ $.Chart.Name }}
  annotations:
    load-balancer.hetzner.cloud/name: "os2iot-ingress"
spec:
  type: LoadBalancer
  ports:
    - name: udp
      port: 1700
      targetPort: 1700
      protocol: UDP
  selector:
    app: {{ $.Chart.Name }}
