chirpstackGateway:
  image:
    registry: chirpstack
    repository: chirpstack-gateway-bridge
    tag: '4.0.10'
    pullPolicy: IfNotPresent

  replicaCount: 1

  # Node selector for pod scheduling (e.g., restrict to specific region)
  nodeSelector:
    topology.kubernetes.io/region: fsn1

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  mqtt:
    server: "tcp://mosquitto-svc.mosquitto:1883"
