kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $.Chart.Name }}
spec:
  replicas: {{ .Values.os2iotFrontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
        version: "{{ $.Chart.Name }}-{{ .Values.os2iotFrontend.image.tag }}"
    spec:
      {{- with .Values.os2iotFrontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ .Values.os2iotFrontend.image.registry }}/{{ .Values.os2iotFrontend.image.repository }}:{{ .Values.os2iotFrontend.image.tag }}"
          imagePullPolicy: {{ .Values.os2iotFrontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.os2iotFrontend.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.os2iotFrontend.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ $.Chart.Name }}-configmap
      restartPolicy: Always
