kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $.Chart.Name }}
spec:
  replicas: {{ .Values.zookeeper.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
        version: "{{ $.Chart.Name }}-{{ .Values.zookeeper.image.tag }}"
    spec:
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ .Values.zookeeper.image.registry }}/{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}"
          imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy }}
          ports:
            - name: admin
              containerPort: 2181
              protocol: TCP
          resources:
            {{- toYaml .Values.zookeeper.resources | nindent 12 }}
          # Custom bellow: 
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "{{ $.Values.zookeeper.allow_anonymous_login }}"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "{{ $.Values.zookeeper.clientPort }}"
            - name: ZOOKEEPER_TICK_TIME
              value: "{{ $.Values.zookeeper.tickTime }}"
      restartPolicy: Always
