chirpstack:
  # Default values for aodb.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  image:
    registry: chirpstack
    repository: chirpstack
    tag: '4.6'
    pullPolicy: IfNotPresent

  replicaCount: 1

  # Node selector for pod scheduling (e.g., restrict to specific region)
  nodeSelector:
    topology.kubernetes.io/region: fsn1

  ingress:
    host: chirpstack.os2iot.itkdev.dk

  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

  extraEnv: []

  MQTT:
   server: "tcp://mosquitto-svc.mosquitto:1883"

  redis:
    url: "redis://chirpstack-redis:6379/0"

  network:
    net_id: "000000"
    adr_plugins: '[]'
    enabled_regions: '["eu868"]'

  api:
    bind: "0.0.0.0:8080"
