os2iotFrontend:
  image:
    registry: ghcr.io/itk-dev
    repository: os2iot-frontend
    tag: 'latest'
    pullPolicy: Always

  replicaCount: 1

  # Node selector for pod scheduling (e.g., restrict to specific region)
  nodeSelector:
    topology.kubernetes.io/region: fsn1

  service:
    port: 8081

  containerPort: 8081

  ingress:
    host: os2iot.itkdev.dk

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

  config:
    production: "true"
    baseUrl: "/api/v1/"
    tablePageSize: "25"
    enableKombit: "false"