{{- range $.Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argo-cd
  {{- if .syncWave }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .syncWave }}"
  {{- end }}
spec:
  project: {{ .project }}
  source:
    repoURL: {{ $.Values.repoUrl }}
    path: applications/{{ .path | default .name }}
    targetRevision: HEAD
    helm:
      {{- if .releaseName }}
      releaseName: {{ .releaseName }}
      {{- end }}
      {{- if .valueFiles }}
      valueFiles: {{ .valueFiles | toYaml | nindent 8}}
      {{-  end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
  syncPolicy:
    {{- if .automated }}
    automated: {}
    {{- end }}
    retry:
      limit: 5
      backoff:
        duration: 30s
        maxDuration: 5m
        factor: 2
    syncOptions:
      - CreateNamespace=true
    {{- range .syncOptions }}
      - {{ . }}
    {{- end }}
{{- end }}
