zookeeper:
  image:
    registry: confluentinc
    repository: cp-zookeeper
    tag: '7.6.0'
    pullPolicy: IfNotPresent

  replicaCount: 1

  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

  allow_anonymous_login: "yes"
  clientPort: 2181
  tickTime: 2000
