zookeeper:
  image:
    registry: confluentinc
    repository: cp-zookeeper
    tag: '7.6.0'
    pullPolicy: IfNotPresent

  replicaCount: 1

  resources:
    limits:
      cpu: 150m
      memory: 512Mi
    requests:
      cpu: 5m
      memory: 128Mi

  allow_anonymous_login: "yes"
  clientPort: 2181
  tickTime: 2000
