apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chirpstack-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - {{ .Values.chirpstack.ingress.host }}
    secretName: chirpstack-tls
  rules:
  - host: {{ .Values.chirpstack.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chirpstack-clusterip-svc
            port:
              number: 8081
