apiVersion: v1
kind: ConfigMap
metadata:
  name: fip-controller-config
  namespace: kube-system
data:
  config.json: |
    {
      "hcloud_floating_ips": {{ .Values.fipController.floatingIPs | toJson }},
      "node_address_type": {{ .Values.fipController.nodeAddressType | quote }},
      "namespace": "kube-system"
    }
