kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $.Chart.Name }}
spec:
  replicas: {{ .Values.kafka.replicaCount}}
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
        version: "{{ $.Chart.Name }}-{{ .Values.kafka.image.tag }}"
    spec:
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ .Values.kafka.image.registry }}/{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
          imagePullPolicy: {{ .Values.kafka.image.pullPolicy }}
          ports:
            - name: plaintext
              containerPort: 9092
              protocol: TCP
            - name: internal
              containerPort: 9093
              protocol: TCP
          resources:
            {{- toYaml .Values.kafka.resources | nindent 12 }}
          # Custom bellow: 
          env:
            - name: KAFKA_BROKER_ID
              value: "{{ $.Values.kafka.configuration.broker_id }}"
            - name: KAFKA_LISTENERS
              value: "{{ $.Values.kafka.configuration.listeners }}"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "{{ $.Values.kafka.configuration.advertised_listeners }}"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "{{ $.Values.kafka.configuration.listener_security_protocol_map }}"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "{{ $.Values.kafka.configuration.zookeeper_connect }}"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "{{ $.Values.kafka.configuration.allow_plaintext_listener }}"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "{{ $.Values.kafka.configuration.inter_broker_listener_name }}"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "{{ $.Values.kafka.configuration.offsets_topic_replication_factor | default 1 }}"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "{{ $.Values.kafka.configuration.transaction_state_log_replication_factor | default 1 }}"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "{{ $.Values.kafka.configuration.transaction_state_log_min_isr | default 1 }}"
          startupProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
      restartPolicy: Always
